// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: zeus_futures_company_msg.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Zeus.RPC.Protocol {
  public static partial class FuturesCompanyRpcService
  {
    static readonly string __ServiceName = "Zeus.RPC.Protocol.FuturesCompanyRpcService";

    static readonly grpc::Marshaller<global::Zeus.RPC.Protocol.FuturesCompanysReq> __Marshaller_Zeus_RPC_Protocol_FuturesCompanysReq = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Zeus.RPC.Protocol.FuturesCompanysReq.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Zeus.RPC.Protocol.FuturesCompanysResp> __Marshaller_Zeus_RPC_Protocol_FuturesCompanysResp = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Zeus.RPC.Protocol.FuturesCompanysResp.Parser.ParseFrom);

    static readonly grpc::Method<global::Zeus.RPC.Protocol.FuturesCompanysReq, global::Zeus.RPC.Protocol.FuturesCompanysResp> __Method_Get = new grpc::Method<global::Zeus.RPC.Protocol.FuturesCompanysReq, global::Zeus.RPC.Protocol.FuturesCompanysResp>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Get",
        __Marshaller_Zeus_RPC_Protocol_FuturesCompanysReq,
        __Marshaller_Zeus_RPC_Protocol_FuturesCompanysResp);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Zeus.RPC.Protocol.ZeusFuturesCompanyMsgReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of FuturesCompanyRpcService</summary>
    [grpc::BindServiceMethod(typeof(FuturesCompanyRpcService), "BindService")]
    public abstract partial class FuturesCompanyRpcServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Zeus.RPC.Protocol.FuturesCompanysResp> Get(global::Zeus.RPC.Protocol.FuturesCompanysReq request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for FuturesCompanyRpcService</summary>
    public partial class FuturesCompanyRpcServiceClient : grpc::ClientBase<FuturesCompanyRpcServiceClient>
    {
      /// <summary>Creates a new client for FuturesCompanyRpcService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public FuturesCompanyRpcServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for FuturesCompanyRpcService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public FuturesCompanyRpcServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected FuturesCompanyRpcServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected FuturesCompanyRpcServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Zeus.RPC.Protocol.FuturesCompanysResp Get(global::Zeus.RPC.Protocol.FuturesCompanysReq request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Get(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Zeus.RPC.Protocol.FuturesCompanysResp Get(global::Zeus.RPC.Protocol.FuturesCompanysReq request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Get, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Zeus.RPC.Protocol.FuturesCompanysResp> GetAsync(global::Zeus.RPC.Protocol.FuturesCompanysReq request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Zeus.RPC.Protocol.FuturesCompanysResp> GetAsync(global::Zeus.RPC.Protocol.FuturesCompanysReq request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Get, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override FuturesCompanyRpcServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new FuturesCompanyRpcServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(FuturesCompanyRpcServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Get, serviceImpl.Get).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, FuturesCompanyRpcServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Get, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Zeus.RPC.Protocol.FuturesCompanysReq, global::Zeus.RPC.Protocol.FuturesCompanysResp>(serviceImpl.Get));
    }

  }
}
#endregion
