// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: zeus_userlog_msg.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Zeus.RPC.Protocol {
  public static partial class UserLogRpcService
  {
    static readonly string __ServiceName = "Zeus.RPC.Protocol.UserLogRpcService";

    static readonly grpc::Marshaller<global::Zeus.RPC.Protocol.UserLogReq> __Marshaller_Zeus_RPC_Protocol_UserLogReq = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Zeus.RPC.Protocol.UserLogReq.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Zeus.RPC.Protocol.UserLogResp> __Marshaller_Zeus_RPC_Protocol_UserLogResp = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Zeus.RPC.Protocol.UserLogResp.Parser.ParseFrom);

    static readonly grpc::Method<global::Zeus.RPC.Protocol.UserLogReq, global::Zeus.RPC.Protocol.UserLogResp> __Method_AddUserLog = new grpc::Method<global::Zeus.RPC.Protocol.UserLogReq, global::Zeus.RPC.Protocol.UserLogResp>(
        grpc::MethodType.Unary,
        __ServiceName,
        "AddUserLog",
        __Marshaller_Zeus_RPC_Protocol_UserLogReq,
        __Marshaller_Zeus_RPC_Protocol_UserLogResp);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Zeus.RPC.Protocol.ZeusUserlogMsgReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of UserLogRpcService</summary>
    [grpc::BindServiceMethod(typeof(UserLogRpcService), "BindService")]
    public abstract partial class UserLogRpcServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Zeus.RPC.Protocol.UserLogResp> AddUserLog(global::Zeus.RPC.Protocol.UserLogReq request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for UserLogRpcService</summary>
    public partial class UserLogRpcServiceClient : grpc::ClientBase<UserLogRpcServiceClient>
    {
      /// <summary>Creates a new client for UserLogRpcService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public UserLogRpcServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for UserLogRpcService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public UserLogRpcServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected UserLogRpcServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected UserLogRpcServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Zeus.RPC.Protocol.UserLogResp AddUserLog(global::Zeus.RPC.Protocol.UserLogReq request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddUserLog(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Zeus.RPC.Protocol.UserLogResp AddUserLog(global::Zeus.RPC.Protocol.UserLogReq request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_AddUserLog, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Zeus.RPC.Protocol.UserLogResp> AddUserLogAsync(global::Zeus.RPC.Protocol.UserLogReq request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddUserLogAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Zeus.RPC.Protocol.UserLogResp> AddUserLogAsync(global::Zeus.RPC.Protocol.UserLogReq request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_AddUserLog, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override UserLogRpcServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new UserLogRpcServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(UserLogRpcServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_AddUserLog, serviceImpl.AddUserLog).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, UserLogRpcServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_AddUserLog, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Zeus.RPC.Protocol.UserLogReq, global::Zeus.RPC.Protocol.UserLogResp>(serviceImpl.AddUserLog));
    }

  }
}
#endregion
